// This file is automatically generated. Do not modify it manually.

// TODO: Replace with your Firebase project configuration.
// See: https://firebase.google.com/docs/web/learn-more#config-object
export const firebaseConfig = {
  apiKey: "REPLACE_WITH_YOUR_API_KEY",
  authDomain: "REPLACE_WITH_YOUR_AUTH_DOMAIN",
  projectId: "REPLACE_WITH_YOUR_PROJECT_ID",
  storageBucket: "REPLACE_WITH_YOUR_STORAGE_BUCKET",
  messagingSenderId: "REPLACE_WITH_YOUR_MESSAGING_SENDER_ID",
  appId: "REPLACE_WITH_YOUR_APP_ID",
};

// This is a public configuration and can be safely exposed to the client.
// See: https://firebase.google.com/docs/projects/learn-more#config-files-objects
if (firebaseConfig.apiKey === "REPLACE_WITH_YOUR_API_KEY") {
  console.warn(`
    Firebase is not configured. Please create a new Firebase project
    and add your project configuration to src/firebase/config.ts.
    See: https://firebase.google.com/docs/web/setup#add-sdk-and-initialize
  `);
}
