// This file is automatically generated. Do not modify it manually.

export const firebaseConfig = {
  projectId: "studio-1279970876-eb44b",
  appId: "1:94656361680:web:2d7ccb22b8b1ef16fa5ad5",
  apiKey: "AIzaSyCgENzeoS1f3JI-5mGuREinsCexHl9ZICc",
  authDomain: "studio-1279970876-eb44b.firebaseapp.com",
  messagingSenderId: "94656361680",
};

// This is a public configuration and can be safely exposed to the client.
// See: https://firebase.google.com/docs/projects/learn-more#config-files-objects
if (firebaseConfig.apiKey === "REPLACE_WITH_YOUR_API_KEY") {
  console.warn(`
    Firebase is not configured. Please create a new Firebase project
    and add your project configuration to src/firebase/config.ts.
    See: https://firebase.google.com/docs/web/setup#add-sdk-and-initialize
  `);
}
